server:
  port: 8072
spring:
  profiles:
    active: dev #默认为开发环境
  application:
    name: mall-portal-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: Bearer  #JWT负载中拿到开头

# 自定义redis key
redis:
  member: 'mall:ums:member:'
  database: mall
  key:
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
    member: 'ums:member'
  expire:
    authCode: 90 # 验证码超期时间
    common: 86400 # 24小时


# 消息队列定义
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue

